export const apeItems = [
  {
    alt: 'ape1',
    apeMob1x: '../../../images/apeCollection/mob/Ape1mob1x-min.jpg',
    apeMob2x: '../../../images/apeCollection/mob/Ape1mob2x-min.jpg',
    apeBig1x: '../../../images/apeCollection/tab_desk/Ape1big1x-min.jpg',
    apeBig2x: '../../../images/apeCollection/tab_desk/Ape1big2x-min.jpg',
  },
  {
    alt: 'ape2',
    apeMob1x: '/images/apeCollection/mob/Ape2mob1x-min.jpg',
    apeMob2x: '/images/apeCollection/mob/Ape2mob2x-min.jpg',
    apeBig1x: '/images/apeCollection/tab_desk/Ape2big1x-min.jpg',
    apeBig2x: '/images/apeCollection/tab_desk/Ape2big2x-min.jpg',
  },
  {
    alt: 'ape3',
    apeMob1x: '/src/images/apeCollection/mob/Ape3mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape3mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape3big1x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape3big2x-min.jpg',
  },
  {
    alt: 'ape4',
    apeMob1x: '/src/images/apeCollection/mob/Ape4mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape4mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape4big1x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape4big2x-min.jpg',
  },
  {
    alt: 'ape5',
    apeMob1x: '/src/images/apeCollection/mob/Ape5mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape5mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape1big5x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape1big5x-min.jpg',
  },
  {
    alt: 'ape6',
    apeMob1x: '/src/images/apeCollection/mob/Ape6mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape6mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape6big1x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape6big2x-min.jpg',
  },
  {
    alt: 'ape7',
    apeMob1x: '/src/images/apeCollection/mob/Ape7mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape7mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape7big1x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape7big2x-min.jpg',
  },
  {
    alt: 'ape8',
    apeMob1x: '/src/images/apeCollection/mob/Ape8mob1x-min.jpg',
    apeMob2x: '/src/images/apeCollection/mob/Ape8mob2x-min.jpg',
    apeBig1x: '/src/images/apeCollection/tab_desk/Ape8big1x-min.jpg',
    apeBig2x: '/src/images/apeCollection/tab_desk/Ape8big2x-min.jpg',
  },
];
